---
- name: Add maintenance tasks to cron (loop)
  ansible.builtin.cron:
    name: "{{ item.value.name }}"
    minute: "{{ item.value.minute }}"
    hour: "{{ item.value.hour }}"
    dom: "{{ item.value.dom }}"
    month: "{{ item.value.month }}"
    dow: "{{ item.value.dow }}"
    job: "{{ item.value.job }}"
    user: "{{ item.value.user }}"
  loop: "{{ fsm_cron_tasks | dict2items }}"
  when: "item.value.enable | bool"
